# Generated by Django 3.2.4 on 2021-06-24 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210623_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 10, 4, 34, 256015, tzinfo=utc)),
        ),
    ]
